### ISSUE TITLE
An exception occured in Raknet using b51

### ISSUE THREAD

**Issue by HandyHat** [bundabrg/Geyser#12]
**Describe the bug**
Upon trying to connect, the following error occurs:
` [com.nukkitx.network.raknet.RakNetServer] An exception occurred in RakNet
java.lang.NullPointerException: Cannot invoke "org.geysermc.connector.network.session.GeyserSession.getPlayerEntity()" because "session" is null
        at org.geysermc.connector.skin.SkinManager$GameProfileData.from(SkinManager.java:278) ~[?:?]
        at org.geysermc.connector.skin.SkinManager.buildCachedEntry(SkinManager.java:53) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession.connect(GeyserSession.java:385) ~[?:?]
        at org.geysermc.connector.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:127) ~[?:?]
        at com.nukkitx.protocol.bedrock.packet.ResourcePackClientResponsePacket.handle(ResourcePackClientResponsePacket.java:20) ~[?:?]
        at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:288) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]`

**Server Version**
`git-Paper-395 (MC: 1.16.4)`

**Geyser Version**
`Geyser-Spigot-v1.16-b51.jar`

**Minecraft: Bedrock Edition Version**
`v1.16.201` of `Minecraft: Windows 10 Edition`

**Additional Context**
https://dump.geysermc.org/8oxZ6ImVwcSxEebwWbOJYR5uMKZRbei3

Issue doesn't occue on `Geyser-Spigot-v1.16-b50.jar` or the offical Geyser builds. Can be reproduced when the only plugins are Geyser and Floodgate. Happens both with and without Geyser-Reversion.

**Comment by bundabrg** [comment]
I think this may be fixed in b52. Please re-open if it still occurs.
