### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by bundabrg** [bundabrg/Geyser#2]
```
[11:13:35 ERROR] Could not translate packet ServerUnloadChunkPacket
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
        at org.geysermc.connector.network.translators.java.world.JavaUnloadChunkTranslator.translate(JavaUnloadChunkTranslator.java:48) ~[Geyser-2020061201.jar:?]
        at org.geysermc.connector.network.translators.java.world.JavaUnloadChunkTranslator.translate(JavaUnloadChunkTranslator.java:38) ~[Geyser-2020061201.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:73) [Geyser-2020061201.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:381) [Geyser-2020061201.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-2020061201.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-2020061201.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-2020061201.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by bundabrg** [comment]
Fixed in 60fd88cd1b1d4254d6b9f8d20898829caa247ebc
