### ISSUE TITLE
emoticon error

### ISSUE THREAD

**Issue by WesleyVanNeck** [bundabrg/Geyser#4]
`[14:12:23] [Network Listener - #1/INFO] [Geyser-BungeeCord]: Player connected with username LegacyGamer7025
[14:12:24] [Network Listener - #1/WARN] [Geyser-BungeeCord]: Could not translate packet EmoteListPacket
java.lang.ClassCastException: com.nukkitx.protocol.bedrock.packet.EmoteListPacket cannot be cast to com.nukkitx.protocol.bedrock.packet.EmotePacket
	at org.geysermc.connector.network.translators.bedrock.BedrockEmoteTranslator.translate(BedrockEmoteTranslator.java:35) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:77) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:51) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:157) ~[?:?]
	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:772) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.EmoteListPacket.handle(EmoteListPacket.java:21) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[14:12:24] [Network Listener - #1/ERROR]: java.lang.ClassCastException: com.nukkitx.protocol.bedrock.packet.EmoteListPacket cannot be cast to com.nukkitx.protocol.bedrock.packet.EmotePacket
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.connector.network.translators.bedrock.BedrockEmoteTranslator.translate(BedrockEmoteTranslator.java:35)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:77)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:51)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:157)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:772)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.protocol.bedrock.packet.EmoteListPacket.handle(EmoteListPacket.java:21)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
[14:12:24] [Network Listener - #1/ERROR]: 	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[14:12:24] [Network Listener - #1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:12:24] [Network Listener - #1/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by WesleyVanNeck** [comment]
a player will get this with all kind of emotion tingies and this happenst when a player joins

**Comment by bundabrg** [comment]
Fixed in c507e379ef1264eb7ec785f5266800e4cf3c1e35
