### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by WesleyVanNeck** [bundabrg/Geyser#5]
`[14:20:59 WARN] [Geyser-BungeeCord]: Could not translate packet ServerPlayerListEntryPacket
java.lang.ClassCastException: com.github.steveice10.mc.protocol.data.message.TranslationMessage cannot be cast to com.github.steveice10.mc.protocol.data.message.TextMessage
at org.geysermc.connector.utils.MessageUtils.getBedrockMessage(MessageUtils.java:236) ~[?:?]
at org.geysermc.connector.network.translators.java.entity.player.JavaPlayerListEntryTranslator.translate(JavaPlayerListEntryTranslator.java:85) ~[?:?]
at org.geysermc.connector.network.translators.java.entity.player.JavaPlayerListEntryTranslator.translate(JavaPlayerListEntryTranslator.java:42) ~[?:?]
at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:77) ~[?:?]
at org.geysermc.connector.network.session.GeyserSession$1.lambda$packetReceived$2(GeyserSession.java:444) ~[?:?]
at org.geysermc.connector.event.EventManager$TriggerResult.onNotCancelled(EventManager.java:185) ~[?:?]
at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:443) ~[?:?]
at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[14:20:59 ERROR]: java.lang.ClassCastException: com.github.steveice10.mc.protocol.data.message.TranslationMessage cannot be cast to com.github.steveice10.mc.protocol.data.message.TextMessage
[14:20:59 ERROR]: at org.geysermc.connector.utils.MessageUtils.getBedrockMessage(MessageUtils.java:236)
[14:20:59 ERROR]: at org.geysermc.connector.network.translators.java.entity.player.JavaPlayerListEntryTranslator.translate(JavaPlayerListEntryTranslator.java:85)
[14:20:59 ERROR]: at org.geysermc.connector.network.translators.java.entity.player.JavaPlayerListEntryTranslator.translate(JavaPlayerListEntryTranslator.java:42)
[14:20:59 ERROR]: at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:77)
[14:20:59 ERROR]: at org.geysermc.connector.network.session.GeyserSession$1.lambda$packetReceived$2(GeyserSession.java:444)
[14:20:59 ERROR]: at org.geysermc.connector.event.EventManager$TriggerResult.onNotCancelled(EventManager.java:185)
[14:20:59 ERROR]: at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:443)
[14:20:59 ERROR]: at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[14:20:59 ERROR]: at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[14:20:59 ERROR]: at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[14:20:59 ERROR]: at java.lang.Thread.run(Thread.java:748)`

**Comment by WesleyVanNeck** [comment]
happens when tranfering from servers also the player loses skin

**Comment by bundabrg** [comment]
This one is a little odd. I'm unsure why the display name would be a Translation Message. As it causes an exception the whole playerlist packet will be lost.

I'll test using getTranslatedBedrockMessage instead and see if it breaks anything

**Comment by bundabrg** [comment]
Seems to work.

Fixed by 20fc84244fa3bc7d6aa2873685675b6e50f50034
